---
title: "Discussion Assignment 1"
author: "Miguel-Angel Canela, IESE Business School"
date: "September 27, 2018"
output: html_document
---

## Opening file (customize)
```{r}
tata = read.csv('https://raw.githubusercontent.com/iese-bad/DataSci/master/Assignment%201/tata.csv', stringsAsFactors=FALSE)
str(tata)
```

## Cleaning null values for adjusted price
```{r}
price = tata[, 'Adj.Close']
sum(price == 'null')
price = price[price != 'null']
price = as.numeric(price)
str(price)
N = length(price)
```

## Summarizing adjusted price
```{r}
summary(price)
```

## Calculate returns and log returns
```{r}
return = 100 * (price[-1]/price[-N] - 1)
logreturn = 100 * (log(price[-1]) - log(price[-N]))
return[1:25]
logreturn[1:25]
summary(return - logreturn)
```

## Histogram of the returns
```{r}
hist(return, xlab='Daily returns', main='')
```

## Normality
```{r}
mean(abs(return - mean(return)) < 2*sd(return))
```

## Line plot
```{r}
plot(return, type='l', xlab='', ylab='Daily returns')
```
